In [1]:
import pandas as pd

# Load the dataset
train = pd.read_csv("../data/train.csv")

In [2]:
# Lade den Kaggle Test Datensatz
# Dieser muss zusammen mit dem Trainingsdatensatz verarbeitet werden, sonst fehlen einige Spalten im Kaggle Testdatensatz!
X_test_kaggle = pd.read_csv("../data/test.csv")
_X_test_kaggle = X_test_kaggle.copy()

X_test_kaggle["Survived"] = 0 # Dummy damit Pandas keine Zicken macht
X_test_kaggle["IsKaggleTestData"] = True

In [3]:
def transform_data(df:pd.DataFrame):
    # Now the names...
    # First, seperate the first and last name
    df[["LastName", "FirstName_tmp"]] = df["Name"].str.split(",", expand=True)
    
    # Now the salutation forms
    df[["SalutForm","FirstName"]] = df["FirstName_tmp"].str.split(".", n=1, expand=True)
    
    # Grouping family size
    df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
    
    df = df.drop([
        "PassengerId",
        "FirstName_tmp",
        "Name",
        "Cabin",
        "Ticket"], axis=1)
                              
    return df

In [4]:
train = transform_data(train)
X_test_kaggle = transform_data(X_test_kaggle)
train["IsKaggleTestData"] = False

In [5]:
train.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,LastName,SalutForm,FirstName,FamilySize,IsKaggleTestData
0,0,3,male,22.0,1,0,7.2500,S,Braund,Mr,Owen Harris,2,False
1,1,1,female,38.0,1,0,71.2833,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),2,False
2,1,3,female,26.0,0,0,7.9250,S,Heikkinen,Miss,Laina,1,False
3,1,1,female,35.0,1,0,53.1000,S,Futrelle,Mrs,Jacques Heath (Lily May Peel),2,False
4,0,3,male,35.0,0,0,8.0500,S,Allen,Mr,William Henry,1,False

In [6]:
X_test_kaggle.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived,IsKaggleTestData,LastName,SalutForm,FirstName,FamilySize
0,3,male,34.5,0,0,7.8292,Q,0,True,Kelly,Mr,James,1
1,3,female,47.0,1,0,7.0000,S,0,True,Wilkes,Mrs,James (Ellen Needs),2
2,2,male,62.0,0,0,9.6875,Q,0,True,Myles,Mr,Thomas Francis,1
3,3,male,27.0,0,0,8.6625,S,0,True,Wirz,Mr,Albert,1
4,3,female,22.0,1,1,12.2875,S,0,True,Hirvonen,Mrs,Alexander (Helga E Lindqvist),3

In [7]:
df = pd.concat([train, X_test_kaggle], axis=0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Survived          1309 non-null   int64
 1   Pclass            1309 non-null   int64
 2   Sex               1309 non-null   object
 3   Age               1046 non-null   float64
 4   SibSp             1309 non-null   int64
 5   Parch             1309 non-null   int64
 6   Fare              1308 non-null   float64
 7   Embarked          1307 non-null   object
 8   LastName          1309 non-null   object
 9   SalutForm         1309 non-null   object
 10  FirstName         1309 non-null   object
 11  FamilySize        1309 non-null   int64
 12  IsKaggleTestData  1309 non-null   bool
dtypes: bool(1), float64(2), int64(5), object(5)
memory usage: 134.2+ KB

In [30]:
pd.options.display.max_rows = None

df["LastName"].value_counts()

Andersson                 11
Sage                      11
Goodwin                    8
Asplund                    8
Davies                     7
Brown                      6
Panula                     6
Skoog                      6
Carter                     6
Rice                       6
Smith                      6
Fortune                    6
Johnson                    6
Ford                       6
Lefebre                    5
Williams                   5
Ryerson                    5
Palsson                    5
Kelly                      5
Thomas                     5
Baclini                    4
Hansen                     4
Hart                       4
Laroche                    4
Harris                     4
Elias                      4
West                       4
Johnston                   4
Ware                       4
Harper                     4
Boulos                     4
Gustafsson                 4
Johansson                  4
Goldsmith                  4
Dean                       4
Becker                     4
Olsen                      4
Cacic                      4
Vander Planke              4
Herman                     4
Hocking                    4
Allison                    4
Wells                      3
Compton                    3
Jussila                    3
Olsson                     3
Hickman                    3
McCoy                      3
Karlsson                   3
White                      3
Abbott                     3
Svensson                   3
Rosblom                    3
Graham                     3
van Billiard               3
Bourke                     3
Thayer                     3
O'Brien                    3
Douglas                    3
Kink-Heilmann              3
Crosby                     3
Klasen                     3
Newell                     3
Hoyt                       3
Peacock                    3
Collyer                    3
Taussig                    3
Murphy                     3
Navratil                   3
Minahan                    3
Daly                       3
Carlsson                   3
Touma                      3
Mallet                     3
Chapman                    3
Peter                      3
Quick                      3
Hays                       3
Van Impe                   3
Keane                      3
Phillips                   3
Warren                     3
Meyer                      3
Dodge                      3
Widener                    3
Samaan                     3
Nakid                      3
Coutts                     3
Giles                      3
Flynn                      3
Frauenthal                 3
Moubarek                   3
Oreskovic                  3
Jensen                     3
Cor                        3
Nilsson                    3
Howard                     3
Richards                   3
Drew                       3
Danbom                     3
Moran                      3
Spedden                    3
Sandstrom                  3
Wick                       3
Caldwell                   3
Larsson                    2
Angle                      2
Carr                       2
Betros                     2
Snyder                     2
Ryan                       2
Wiklund                    2
Coleff                     2
Hold                       2
Louch                      2
Franklin                   2
Silvey                     2
Thorneycroft               2
Jacobsohn                  2
Jefferys                   2
Kiernan                    2
Cumings                    2
Rothschild                 2
Clarke                     2
Risien                     2
Ali                        2
Beane                      2
Strom                      2
Gale                       2
Harder                     2
Lahtinen                   2
Hamalainen                 2
Hirvonen                   2
Buckley                    2
Foley                      2
Hippach                    2
Aks                        2
Connolly                   2
Stengel                    2
Bishop                     2
Lines                      2
Stanley                    2
Renouf                     2
Khalil                     2
Dennis                     2
Wright                     2
Fleming                    2
Dyker                      2
Penasco y Castellana       2
Andrews                    2
Straus                     2
Beckwith                   2
Duran y More               2
Abelseth                   2
Hagland                    2
Lobb                       2
Abelson                    2
del Carlo                  2
Goldenberg                 2
Kenyon                     2
Bradley                    2
Mellinger                  2
Zakarian                   2
O'Connor                   2
Canavan                    2
Davison                    2
Fox                        2
Morley                     2
Burns                      2
Barbara                    2
Braund                     2
Duff Gordon                2
Andrew                     2
Lennon                     2
Marvin                     2
Lindell                    2
Rogers                     2
Zabour                     2
Attalah                    2
Baxter                     2
Moore                      2
Webber                     2
Turpin                     2
Moor                       2
Robins                     2
Weisz                      2
Nicola-Yarred              2
Holverson                  2
Frolicher-Stehli           2
Hakkarainen                2
Arnold-Franchi             2
Gibson                     2
Faunthorpe                 2
Kimball                    2
Bryhl                      2
Ilmakangas                 2
Chambers                   2
Kink                       2
Carrau                     2
Backstrom                  2
Bowen                      2
Yasbeck                    2
Ostby                      2
Chaffee                    2
Greenfield                 2
Doling                     2
Kantor                     2
Cavendish                  2
Petroff                    2
McNamee                    2
Astor                      2
Pokrnic                    2
Chronopoulos               2
Allen                      2
Jonsson                    2
Karun                      2
Lam                        2
Cardeza                    2
Bonnell                    2
Calic                      2
Saad                       2
McGowan                    2
Watt                       2
Nasser                     2
Cribb                      2
McCarthy                   2
Davidson                   2
Mahon                      2
Taylor                     2
Dick                       2
Caram                      2
Futrelle                   2
Clark                      2
Spencer                    2
Cook                       2
Pears                      2
de Messemaeker             2
Christy                    2
Wilkes                     1
Markoff                    1
Greenberg                  1
Myles                      1
Gill                       1
McEvoy                     1
Hodges                     1
Swift                      1
Troutt                     1
Endres                     1
Fischer                    1
Dooley                     1
Gillespie                  1
Razi                       1
Madill                     1
Soholt                     1
Potter                     1
Behr                       1
Montvila                   1
Shelley                    1
Mullens                    1
Laleff                     1
Silverthorne               1
Gallagher                  1
Markun                     1
Abbing                     1
Najib                      1
Calderhead                 1
Dahlberg                   1
Cleaver                    1
Vander Cruyssen            1
Banfield                   1
Mayne                      1
Balkic                     1
van Melkebeke              1
Roebling                   1
Weir                       1
Sutehall                   1
Humblen                    1
Bystrom                    1
Klaber                     1
Serepeca                   1
Mannion                    1
Alexander                  1
Osman                      1
Ibrahim Shawah             1
Ponesell                   1
Hedman                     1
Brewe                      1
Pettersson                 1
Lester                     1
Hassan                     1
Slemen                     1
Hogeboom                   1
Eklund                     1
Tomlin                     1
Fry                        1
Barah                      1
Mangan                     1
Leader                     1
Gronnestad                 1
Lievens                    1
Otter                      1
Mack                       1
Myhrman                    1
Dantcheff                  1
Tobin                      1
Emanuel                    1
Kilgannon                  1
Robert                     1
Gaskell                    1
Guggenheim                 1
Ayoub                      1
Sjoblom                    1
Wirz                       1
Nirva                      1
Garfirth                   1
Heininen                   1
Chip                       1
Knight                     1
Berriman                   1
Troupiansky                1
Lesurer                    1
Culumovic                  1
Ivanoff                    1
Lemberopolous              1
Nankoff                    1
Long                       1
Hawksford                  1
Mudd                       1
Alhomaki                   1
Marechal                   1
Stranden                   1
Sirota                     1
Rothes                     1
Sinkkonen                  1
Pasic                      1
Allum                      1
Connaghton                 1
Augustsson                 1
Stone                      1
McCormack                  1
Reuchlin                   1
Lulic                      1
Holm                       1
Vande Velde                1
Jonkoff                    1
Bailey                     1
Theobald                   1
Harmer                     1
Pedersen                   1
Abrahim                    1
Chisholm                   1
Abrahamsson                1
Salander                   1
Wenzel                     1
MacKay                     1
Niklasson                  1
Bentham                    1
Midtsjo                    1
Portaluppi                 1
Lyntakoff                  1
McCaffry                   1
Vartanian                  1
Saade                      1
Parker                     1
Oxenham                    1
Mardirosian                1
Rheims                     1
Nasr                       1
Wittevrongel               1
Angheloff                  1
Loring                     1
Karnes                     1
Hyman                      1
Lindstrom                  1
Hiltunen                   1
Rasmussen                  1
Omont                      1
Collett                    1
Rosenbaum                  1
Delalic                    1
Andersen                   1
Finoli                     1
Deacon                     1
Head                       1
Thomson                    1
Reynolds                   1
Candee                     1
McNeill                    1
Everett                    1
Sweet                      1
Willard                    1
Linehan                    1
Vendel                     1
Baccos                     1
Malachard                  1
Sadowitz                   1
Lingane                    1
Payne                      1
Pallas y Castello          1
Wilson                     1
Ismay                      1
Harbeck                    1
Cotterill                  1
Hipkins                    1
Wheeler                    1
Aronsson                   1
Ashby                      1
Gilbert                    1
Hagardon                   1
Colbert                    1
Larsson-Rondberg           1
Conlon                     1
Nourney                    1
Riordan                    1
Naughton                   1
Henriksson                 1
Spector                    1
Oliva y Ocana              1
Riihivouri                 1
Strilic                    1
O'Keefe                    1
Lockyer                    1
Krekorian                  1
Nesson                     1
Rowe                       1
Kreuchen                   1
Assam                      1
Rosenshine                 1
Enander                    1
Dulles                     1
Maguire                    1
de Brito                   1
Denbury                    1
Fillbrook                  1
Lundstrom                  1
Botsford                   1
Whabee                     1
Walcroft                   1
Stokes                     1
Dibden                     1
Julian                     1
Baimbrigge                 1
Salomon                    1
Ilieff                     1
Aldworth                   1
Tucker                     1
Mulvihill                  1
Minkoff                    1
Nieminen                   1
Ovies y Rodriguez          1
Geiger                     1
Keeping                    1
Miles                      1
Cornell                    1
Doyle                      1
Makinen                    1
Case                       1
Demetri                    1
Lamb                       1
Barry                      1
Badman                     1
O'Donoghue                 1
Olsvigen                   1
Guest                      1
Birnbaum                   1
Corey                      1
Bjorklund                  1
McCrae                     1
Dika                       1
Jones                      1
Assaf                      1
Assaf Khalil               1
Flegenheim                 1
Daher                      1
Brady                      1
Mock                       1
Katavelas                  1
Roth                       1
Sap                        1
Hee                        1
Corbett                    1
Peltomaki                  1
Chevre                     1
Shaughnessy                1
Bucknell                   1
Pulbaum                    1
Mangiavacchi               1
Chaudanson                 1
Tenglin                    1
Braf                       1
Veal                       1
Pearce                     1
Crafton                    1
Earnshaw                   1
Matinoff                   1
Storey                     1
Duquemin                   1
Bird                       1
Lundin                     1
Borebank                   1
Smyth                      1
Peruschitz                 1
Nancarrow                  1
Brandeis                   1
Cassebeer                  1
Hellstrom                  1
Lithman                    1
Torfa                      1
Sincock                    1
McCrie                     1
Lane                       1
Maybery                    1
Hilliard                   1
Lindeberg-Lind             1
Beauchamp                  1
Daniels                    1
Johansson Palmquist        1
Holthen                    1
Willer                     1
Swane                      1
Stanton                    1
Shine                      1
Evans                      1
Beattie                    1
Schabert                   1
Carver                     1
Kennedy                    1
Brobeck                    1
Bowenur                    1
Petersen                   1
Spinner                    1
Gracie                     1
Dintcheff                  1
Schmidt                    1
Drapkin                    1
Dakic                      1
LeRoy                      1
Hassab                     1
Sjostedt                   1
Sunderland                 1
Bracken                    1
Green                      1
Nenkoff                    1
Berglund                   1
Mellors                    1
Lovell                     1
Fahlstrom                  1
Leyson                     1
Leonard                    1
Harknett                   1
Pengelly                   1
Hunt                       1
Coleridge                  1
Maenpaa                    1
Lindahl                    1
Reed                       1
Stead                      1
Bazzani                    1
Honkanen                   1
Givard                     1
Perkin                     1
Rood                       1
Romaine                    1
Turcin                     1
Pinsky                     1
Carbines                   1
Andersen-Jensen            1
Lurette                    1
Mernagh                    1
Madigan                    1
Yrois                      1
Vande Walle                1
Johanson                   1
Youseff                    1
Cohen                      1
Albimona                   1
Blank                      1
Cameron                    1
Thorne                     1
Cherry                     1
Ward                       1
Levy                       1
Mineff                     1
Lewy                       1
Hanna                      1
Saalfeld                   1
Francatelli                1
Hendekovic                 1
Moraweck                   1
Danoff                     1
Slayter                    1
Young                      1
Nysveen                    1
Ball                       1
Partner                    1
Denkoff                    1
Dahl                       1
Blackwell                  1
Collander                  1
Haas                       1
Barber                     1
Parrish                    1
Hosono                     1
Harrison                   1
Henry                      1
Reeves                     1
Persson                    1
Bissette                   1
Cairns                     1
Tornquist                  1
Natsch                     1
Healy                      1
Lindblom                   1
Parkes                     1
Duane                      1
de Pelsmaeker              1
Dorking                    1
Stankovic                  1
de Mulder                  1
Naidenoff                  1
Pernot                     1
Hale                       1
Peters                     1
Jenkin                     1
Woolner                    1
Rugg                       1
Novel                      1
Sirayanian                 1
Icard                      1
Stewart                    1
Nye                        1
Crease                     1
Hood                       1
Isham                      1
Bing                       1
Moen                       1
Staneff                    1
Moutal                     1
Dowdell                    1
Waelens                    1
Sheerlinck                 1
McDermott                  1
Nosworthy                  1
O'Driscoll                 1
Devaney                    1
Kraeff                     1
Heikkinen                  1
Saundercock                1
Vestrom                    1
Hewlett                    1
Masselmani                 1
Fynney                     1
Beesley                    1
Sloper                     1
Emir                       1
O'Dwyer                    1
Todoroff                   1
Uruchurtu                  1
Glynn                      1
Wheadon                    1
Mamee                      1
Cann                       1
Ahlin                      1
Ilett                      1
Slocovski                  1
Celotti                    1
Richard                    1
Osen                       1
Giglio                     1
Nysten                     1
Burke                      1
Nicholls                   1
Byles                      1
Bateman                    1
Meo                        1
Gilnagh                    1
Corn                       1
Smiljanic                  1
Bengtsson                  1
Chibnall                   1
Baumann                    1
Ling                       1
Van der hoef               1
Sivola                     1
Newsom                     1
Sobey                      1
Christmann                 1
Coelho                     1
Andreasson                 1

In [10]:
df["FamilySize"].value_counts()

1     790
2     235
3     159
4      43
6      25
5      22
7      16
11     11
8       8
Name: FamilySize, dtype: int64

In [24]:
andersson_fam = df.loc[(df["LastName"] == "Andersson") & (df["FamilySize"] > 6)]

In [25]:
andersson_fam

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,LastName,SalutForm,FirstName,FamilySize,IsKaggleTestData
13,0,3,male,39.0,1,5,31.275,S,Andersson,Mr,Anders Johan,7,False
68,1,3,female,17.0,4,2,7.925,S,Andersson,Miss,Erna Alexandra,7,False
119,0,3,female,2.0,4,2,31.275,S,Andersson,Miss,Ellis Anna Maria,7,False
541,0,3,female,9.0,4,2,31.275,S,Andersson,Miss,Ingeborg Constanzia,7,False
542,0,3,female,11.0,4,2,31.275,S,Andersson,Miss,Sigrid Elisabeth,7,False
610,0,3,female,39.0,1,5,31.275,S,Andersson,Mrs,Anders Johan (Alfrida Konstantia Brogren),7,False
813,0,3,female,6.0,4,2,31.275,S,Andersson,Miss,Ebba Iris Alfrida,7,False
850,0,3,male,4.0,4,2,31.275,S,Andersson,Master,Sigvard Harald Elias,7,False
214,0,3,female,38.0,4,2,7.775,S,Andersson,Miss,Ida Augusta Margareta,7,True

In [13]:
fam_size_11 = df.loc[df["FamilySize"] == 11]

In [14]:
fam_size_11

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,LastName,SalutForm,FirstName,FamilySize,IsKaggleTestData
159,0,3,male,NaN,8,2,69.55,S,Sage,Master,Thomas Henry,11,False
180,0,3,female,NaN,8,2,69.55,S,Sage,Miss,Constance Gladys,11,False
201,0,3,male,NaN,8,2,69.55,S,Sage,Mr,Frederick,11,False
324,0,3,male,NaN,8,2,69.55,S,Sage,Mr,George John Jr,11,False
792,0,3,female,NaN,8,2,69.55,S,Sage,Miss,Stella Anna,11,False
846,0,3,male,NaN,8,2,69.55,S,Sage,Mr,Douglas Bullen,11,False
863,0,3,female,NaN,8,2,69.55,S,Sage,Miss,"Dorothy Edith ""Dolly""",11,False
188,0,3,female,NaN,8,2,69.55,S,Sage,Miss,Ada,11,True
342,0,3,male,NaN,1,9,69.55,S,Sage,Mr,John George,11,True
360,0,3,male,14.5,8,2,69.55,S,Sage,Master,William Henry,11,True
365,0,3,female,NaN,1,9,69.55,S,Sage,Mrs,John (Annie Bullen),11,True

In [120]:
df_copy = df.copy()

In [121]:
df_copy["Family"] = None

In [113]:
def group_families_fam_size(df: pd.DataFrame):
    for fam in df["LastName"].unique():
        tmp_df = df.loc[df["LastName"] == fam ]
        
        unique_fam_sizes = tmp_df["FamilySize"].unique()
        
        i = 0
        for size in unique_fam_sizes:
            df.loc[(df["FamilySize"] == size) & (df["LastName"] == fam), "Family"] = f"{fam}_{i}"
            i = i + 1

In [118]:
def group_families_fare(df: pd.DataFrame):
    for fam in df["LastName"].unique():
        tmp_df = df.loc[df["LastName"] == fam ]
        
        unique_fares = tmp_df["Fare"].unique()
        
        i = 0
        for fare in unique_fares:
            df.loc[(df["Fare"] == fare) & (df["LastName"] == fam), "Family"] = f"{fam}_{i}"
            i = i + 1

In [110]:
group_families_fam_size(df_copy)

In [122]:
group_families_fare(df_copy)

In [94]:
df_copy["Family"].value_counts()

Sage_0                      11
Andersson_0                  9
Goodwin_0                    8
Asplund_0                    7
Panula_0                     6
Fortune_0                    6
Rice_0                       6
Skoog_0                      6
Lefebre_0                    5
Davies_1                     5
Ford_0                       5
Ryerson_0                    5
Kelly_0                      5
Palsson_0                    5
West_0                       4
Allison_0                    4
Cacic_0                      4
Johansson_0                  4
Laroche_0                    4
Smith_0                      4
Dean_0                       4
Johnston_0                   4
Becker_0                     4
Herman_0                     4
Harper_0                     4
Baclini_0                    4
Brown_1                      4
Carter_1                     4
Mallet_0                     3
Svensson_0                   3
Boulos_0                     3
Sandstrom_0                  3
Johnson_0                    3
Nakid_0                      3
Moubarek_0                   3
McCoy_0                      3
Daly_0                       3
Johnson_1                    3
Quick_0                      3
Compton_0                    3
Keane_0                      3
Flynn_0                      3
Rosblom_0                    3
van Billiard_0               3
Caldwell_0                   3
Karlsson_0                   3
Spedden_0                    3
Peter_0                      3
Widener_0                    3
Wick_0                       3
Navratil_0                   3
Hickman_0                    3
Hart_0                       3
Nilsson_0                    3
Elias_0                      3
Olsson_0                     3
Danbom_0                     3
Dodge_0                      3
Touma_0                      3
Wells_0                      3
Bourke_0                     3
Taussig_0                    3
Carlsson_0                   3
Oreskovic_0                  3
Abbott_0                     3
Klasen_0                     3
Goldsmith_0                  3
Coutts_0                     3
Cor_0                        3
Williams_0                   3
Collyer_0                    3
Peacock_0                    3
Samaan_0                     3
Crosby_0                     3
Drew_0                       3
Thayer_0                     3
Van Impe_0                   3
Hippach_0                    2
Dyker_0                      2
Straus_0                     2
del Carlo_0                  2
Khalil_0                     2
Burns_0                      2
Frauenthal_0                 2
Davison_0                    2
Dennis_0                     2
Fox_0                        2
Braund_0                     2
Dick_0                       2
Lahtinen_0                   2
Kiernan_0                    2
Newell_0                     2
Phillips_1                   2
Harris_1                     2
Hoyt_0                       2
Larsson_0                    2
Hold_0                       2
Murphy_0                     2
Hamalainen_0                 2
Beckwith_0                   2
Carter_0                     2
Lobb_0                       2
Zakarian_0                   2
Graham_0                     2
Mellinger_0                  2
Thomas_2                     2
Connolly_0                   2
Bishop_0                     2
Buckley_0                    2
Foley_0                      2
Warren_0                     2
Stengel_0                    2
Fleming_0                    2
Penasco y Castellana_0       2
Abelson_0                    2
Barbara_0                    2
Clarke_0                     2
Harder_0                     2
Jonsson_0                    2
Moor_0                       2
Lindell_0                    2
Chapman_0                    2
Frolicher-Stehli_0           2
Christy_0                    2
Caram_0                      2
de Messemaeker_0             2
Hocking_0                    2
Duff Gordon_0                2
Wright_0                     2
Cumings_0                    2
Thomas_0                     2
Douglas_0                    2
Beane_0                      2
Yasbeck_0                    2
Kimball_0                    2
Bowen_0                      2
Marvin_0                     2
McNamee_0                    2
Cavendish_0                  2
Jensen_0                     2
Ilmakangas_0                 2
Bryhl_0                      2
Chambers_0                   2
Cook_0                       2
Taylor_0                     2
Hansen_1                     2
Astor_0                      2
Cardeza_0                    2
Saad_0                       2
Lam_0                        2
Risien_0                     2
Hays_1                       2
Wiklund_0                    2
Richards_0                   2
Thorneycroft_0               2
Carr_0                       2
Snyder_0                     2
Howard_0                     2
Jefferys_0                   2
Minahan_1                    2
Gale_0                       2
Angle_0                      2
Franklin_0                   2
Smith_1                      2
Davies_0                     2
Abelseth_0                   2
Gustafsson_1                 2
Betros_0                     2
Louch_0                      2
Silvey_0                     2
Hagland_0                    2
Goldenberg_0                 2
Kenyon_0                     2
O'Connor_0                   2
Morley_0                     2
Duran y More_0               2
Giles_0                      2
Aks_0                        2
Lines_0                      2
Stanley_0                    2
Canavan_0                    2
Bradley_0                    2
Rothschild_0                 2
Coleff_0                     2
Ryan_0                       2
Ali_0                        2
Karun_0                      2
Chaffee_0                    2
Webber_0                     2
Watt_0                       2
Moore_0                      2
Calic_0                      2
Baxter_0                     2
Holverson_0                  2
Attalah_0                    2
Jussila_0                    2
Harris_0                     2
Zabour_0                     2
Meyer_0                      2
Weisz_0                      2
Moran_1                      2
Kink_0                       2
Chronopoulos_0               2
Kink-Heilmann_0              2
McGowan_0                    2
Gustafsson_0                 2
Cribb_0                      2
Clark_0                      2
White_0                      2
Williams_1                   2
Robins_0                     2
Rogers_0                     2
Lennon_0                     2
Turpin_0                     2
Gibson_0                     2
Arnold-Franchi_0             2
Faunthorpe_0                 2
Ostby_0                      2
Hakkarainen_0                2
Nicola-Yarred_0              2
Andrew_0                     2
Ware_0                       2
Andersson_1                  2
Vander Planke_1              2
Pears_0                      2
Ware_1                       2
Olsen_0                      2
O'Brien_0                    2
Spencer_0                    2
Pokrnic_0                    2
Allen_0                      2
McCarthy_0                   2
Olsen_1                      2
Nasser_0                     2
Brown_0                      2
Mahon_0                      2
Doling_0                     2
Bonnell_0                    2
Kantor_0                     2
Greenfield_0                 2
Carrau_0                     2
Petroff_0                    2
Futrelle_0                   2
Lester_0                     1
Bystrom_0                    1
Alexander_0                  1
Dulles_0                     1
Swift_0                      1
Slemen_0                     1
Maguire_0                    1
Hansen_2                     1
Meyer_1                      1
Gill_0                       1
Roebling_0                   1
Pettersson_0                 1
Enander_0                    1
van Melkebeke_0              1
Strilic_0                    1
Andrews_1                    1
Balkic_0                     1
Vander Cruyssen_0            1
Riihivouri_0                 1
Hedman_0                     1
Najib_0                      1
Laleff_0                     1
Ponesell_0                   1
Ibrahim Shawah_0             1
Rosenshine_0                 1
Razi_0                       1
Marechal_0                   1
de Brito_0                   1
Stokes_0                     1
Alhomaki_0                   1
Chip_0                       1
Sirota_0                     1
Botsford_0                   1
Mudd_0                       1
Serepeca_0                   1
Pasic_0                      1
Whabee_0                     1
Allum_0                      1
Giles_1                      1
Lemberopolous_0              1
Augustsson_0                 1
Walcroft_0                   1
Stone_0                      1
Dibden_0                     1
Denbury_0                    1
McCormack_0                  1
Reuchlin_0                   1
Culumovic_0                  1
Abbing_0                     1
Julian_0                     1
Lulic_0                      1
Lockyer_0                    1
Markoff_0                    1
Holm_0                       1
O'Keefe_0                    1
Fillbrook_0                  1
Heininen_0                   1
Fry_0                        1
Lundstrom_0                  1
Tomlin_0                     1
Ismay_0                      1
Osman_0                      1
Berriman_0                   1
Renouf_1                     1
Mannion_0                    1
Riordan_0                    1
Nourney_0                    1
Conlon_0                     1
Hassan_0                     1
Knight_0                     1
Larsson-Rondberg_0           1
Troupiansky_0                1
Hodges_0                     1
Lesurer_0                    1
Ivanoff_0                    1
Nankoff_0                    1
Hawksford_0                  1
Colbert_0                    1
Stranden_0                   1
Sinkkonen_0                  1
Kink-Heilmann_1              1
Naughton_0                   1
Gillespie_0                  1
Pallas y Castello_0          1
Calderhead_0                 1
Oliva y Ocana_0              1
Weir_0                       1
Chapman_1                    1
Mullens_0                    1
Humblen_0                    1
Spector_0                    1
Silverthorne_0               1
Gallagher_0                  1
Cleaver_0                    1
Jensen_1                     1
Henriksson_0                 1
Mayne_0                      1
Klaber_0                     1
Greenberg_0                  1
Soholt_0                     1
Endres_0                     1
Troutt_0                     1
McEvoy_0                     1
Gilbert_0                    1
Connaghton_0                 1
Payne_0                      1
Assam_0                      1
Myhrman_0                    1
Tobin_0                      1
Emanuel_0                    1
Harbeck_0                    1
Kilgannon_0                  1
Robert_0                     1
Ayoub_0                      1
Long_0                       1
Harmer_0                     1
Ashby_0                      1
Sjoblom_0                    1
Guggenheim_0                 1
Gaskell_0                    1
Hoyt_1                       1
Dantcheff_0                  1
Otter_0                      1
Leader_0                     1
Wilson_0                     1
Hocking_1                    1
Cotterill_0                  1
Elias_1                      1
Mack_0                       1
Aronsson_0                   1
Wheeler_0                    1
Vande Velde_0                1
Jonkoff_0                    1
Hipkins_0                    1
Bailey_0                     1
Theobald_0                   1
Rothes_0                     1
Garfirth_0                   1
Nirva_0                      1
Barah_0                      1
Eklund_0                     1
Hogeboom_0                   1
Brewe_0                      1
Mangan_0                     1
Gronnestad_0                 1
Lievens_0                    1
Potter_0                     1
Murphy_1                     1
Shelley_0                    1
Petersen_0                   1
Beattie_0                    1
Vendel_0                     1
Schabert_0                   1
Linehan_0                    1
Carver_0                     1
Kennedy_0                    1
Brobeck_0                    1
Bowenur_0                    1
Willard_0                    1
Lindeberg-Lind_0             1
Spinner_0                    1
Gracie_0                     1
Dintcheff_0                  1
Sweet_0                      1
Hocking_2                    1
Schmidt_0                    1
Drapkin_0                    1
Daniels_0                    1
Baccos_0                     1
Evans_0                      1
Shine_0                      1
Stanton_0                    1
Bentham_0                    1
Niklasson_0                  1
MacKay_0                     1
Braf_0                       1
Nancarrow_0                  1
Wenzel_0                     1
Salander_0                   1
Abrahamsson_0                1
Karnes_0                     1
Johansson Palmquist_0        1
Thomas_1                     1
Holthen_0                    1
Hyman_0                      1
Lindstrom_0                  1
Willer_0                     1
Hiltunen_0                   1
Swane_0                      1
Beauchamp_0                  1
Vander Planke_2              1
Midtsjo_0                    1
Maybery_0                    1
Lithman_0                    1
Deacon_0                     1
Torfa_0                      1
Sincock_0                    1
McCrie_0                     1
Lane_0                       1
Finoli_0                     1
Douglas_1                    1
Andersen_0                   1
Hilliard_0                   1
Delalic_0                    1
Rosenbaum_0                  1
Veal_0                       1
Salomon_0                    1
Lingane_0                    1
Collett_0                    1
Baimbrigge_0                 1
Omont_0                      1
Hellstrom_0                  1
Cassebeer_0                  1
Brandeis_0                   1
Peruschitz_0                 1
Everett_0                    1
McNeill_0                    1
Crafton_0                    1
Earnshaw_0                   1
Matinoff_0                   1
Asplund_1                    1
Candee_0                     1
Reynolds_0                   1
Storey_0                     1
Duquemin_0                   1
Bird_0                       1
Lundin_0                     1
Thomson_0                    1
Borebank_0                   1
Head_0                       1
Smyth_0                      1
Pearce_0                     1
Tenglin_0                    1
Birnbaum_0                   1
Markun_0                     1
Malachard_0                  1
Jones_0                      1
Vartanian_0                  1
Assaf_0                      1
Assaf Khalil_0               1
Flegenheim_0                 1
Daher_0                      1
Brady_0                      1
Mock_0                       1
Katavelas_0                  1
Chevre_0                     1
Roth_0                       1
Sap_0                        1
Loring_0                     1
Hee_0                        1
Angheloff_0                  1
Wittevrongel_0               1
Goldsmith_1                  1
Corbett_0                    1
Sadowitz_0                   1
Ilieff_0                     1
Abrahim_0                    1
White_1                      1
Dahlberg_0                   1
Kreuchen_0                   1
Banfield_0                   1
Rowe_0                       1
Sutehall_0                   1
Nesson_0                     1
Montvila_0                   1
Krekorian_0                  1
Graham_1                     1
Behr_0                       1
Dooley_0                     1
Wilkes_0                     1
Myles_0                      1
Wirz_0                       1
Rasmussen_0                  1
Hirvonen_1                   1
Hagardon_0                   1
Peltomaki_0                  1
Shaughnessy_0                1
Guest_0                      1
Howard_1                     1
Cornell_0                    1
Aldworth_0                   1
Saade_0                      1
Doyle_0                      1
McCaffry_0                   1
Case_0                       1
Demetri_0                    1
Lamb_0                       1
Barry_0                      1
Nasr_0                       1
Warren_1                     1
Badman_0                     1
Chisholm_0                   1
O'Donoghue_0                 1
Lyntakoff_0                  1
Portaluppi_0                 1
Pedersen_0                   1
Davidson_1                   1
Miles_0                      1
Keeping_0                    1
Geiger_0                     1
Ovies y Rodriguez_0          1
Bucknell_0                   1
Pulbaum_0                    1
Rheims_0                     1
Mangiavacchi_0               1
Chaudanson_0                 1
Ford_1                       1
Mardirosian_0                1
Dika_0                       1
McCrae_0                     1
Bjorklund_0                  1
Corey_0                      1
Tucker_0                     1
Mulvihill_0                  1
Oxenham_0                    1
Minkoff_0                    1
Nieminen_0                   1
Parker_0                     1
Makinen_0                    1
Ohman_0                      1
Madill_0                     1
Sunderland_0                 1
Green_0                      1
Nenkoff_0                    1
Berglund_0                   1
Mellors_0                    1
Lovell_0                     1
Fahlstrom_0                  1
Sjostedt_0                   1
Leyson_0                     1
Harknett_0                   1
Pengelly_0                   1
Hunt_0                       1
Coleridge_0                  1
Maenpaa_0                    1
Minahan_0                    1
Lindahl_0                    1
Reed_0                       1
Strom_1                      1
Stead_0                      1
Thorne_0                     1
Bracken_0                    1
Bazzani_0                    1
Ward_0                       1
Jacobsohn_0                  1
Pinsky_0                     1
Carbines_0                   1
Andersen-Jensen_0            1
Lurette_0                    1
Mernagh_0                    1
Madigan_0                    1
Yrois_0                      1
Vande Walle_0                1
Johanson_0                   1
Youseff_0                    1
Cohen_0                      1
Strom_0                      1
Backstrom_1                  1
Albimona_0                   1
Blank_0                      1
Cameron_0                    1
Perkin_0                     1
Givard_0                     1
Honkanen_0                   1
Cherry_0                     1
Parrish_0                    1
Yousif_0                     1
Mineff_0                     1
Hanna_0                      1
Saalfeld_0                   1
Francatelli_0                1
Hays_0                       1
Hendekovic_0                 1
Moraweck_0                   1
Danoff_0                     1
Slayter_0                    1
Young_0                      1
Nysveen_0                    1
Ball_0                       1
Partner_0                    1
Denkoff_0                    1
Dahl_0                       1
Blackwell_0                  1
Collander_0                  1
Sedgwick_0                   1
Dimic_0                      1
Odahl_0                      1
Lewy_0                       1
Haas_0                       1
Harrison_0                   1
Levy_0                       1
Henry_0                      1
Reeves_0                     1
Persson_0                    1
Bissette_0                   1
Cairns_0                     1
Tornquist_0                  1
Natsch_0                     1
Healy_0                      1
Andrews_0                    1
Lindblom_0                   1
Parkes_0                     1

In [98]:
andersson_fam = df_copy.loc[(df_copy["LastName"] == "Andersson") & (df_copy["FamilySize"] > 6)]

In [99]:
andersson_fam

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,LastName,SalutForm,FirstName,FamilySize,IsKaggleTestData,Family
13,0,3,male,39.0,1,5,31.275,S,Andersson,Mr,Anders Johan,7,False,Andersson_0
68,1,3,female,17.0,4,2,7.925,S,Andersson,Miss,Erna Alexandra,7,False,Andersson_0
119,0,3,female,2.0,4,2,31.275,S,Andersson,Miss,Ellis Anna Maria,7,False,Andersson_0
541,0,3,female,9.0,4,2,31.275,S,Andersson,Miss,Ingeborg Constanzia,7,False,Andersson_0
542,0,3,female,11.0,4,2,31.275,S,Andersson,Miss,Sigrid Elisabeth,7,False,Andersson_0
610,0,3,female,39.0,1,5,31.275,S,Andersson,Mrs,Anders Johan (Alfrida Konstantia Brogren),7,False,Andersson_0
813,0,3,female,6.0,4,2,31.275,S,Andersson,Miss,Ebba Iris Alfrida,7,False,Andersson_0
850,0,3,male,4.0,4,2,31.275,S,Andersson,Master,Sigvard Harald Elias,7,False,Andersson_0
214,0,3,female,38.0,4,2,7.775,S,Andersson,Miss,Ida Augusta Margareta,7,True,Andersson_0

In [123]:
fams = df_copy.loc[(df_copy["FamilySize"] > 1)]

In [124]:
fams.sort_values("Family")

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,LastName,SalutForm,FirstName,FamilySize,IsKaggleTestData,Family
746,0,3,male,16.00,1,1,20.2500,S,Abbott,Mr,Rossmore Edward,3,False,Abbott_0
279,1,3,female,35.00,1,1,20.2500,S,Abbott,Mrs,Stanton (Rosa Hunt),3,False,Abbott_0
392,0,3,male,13.00,0,2,20.2500,S,Abbott,Master,Eugene Joseph,3,True,Abbott_0
874,1,2,female,28.00,1,0,24.0000,C,Abelson,Mrs,Samuel (Hannah Wizosky),2,False,Abelson_0
308,0,2,male,30.00,1,0,24.0000,C,Abelson,Mr,Samuel,2,False,Abelson_0
40,0,3,female,40.00,1,0,9.4750,S,Ahlin,Mrs,Johan (Johanna Persdotter Larsson),2,False,Ahlin_0
855,1,3,female,18.00,0,1,9.3500,S,Aks,Mrs,Sam (Leah Rosen),2,False,Aks_0
307,0,3,male,0.83,0,1,9.3500,S,Aks,Master,Philip Frank,2,True,Aks_0
297,0,1,female,2.00,1,2,151.5500,S,Allison,Miss,Helen Loraine,4,False,Allison_0
305,1,1,male,0.92,1,2,151.5500,S,Allison,Master,Hudson Trevor,4,False,Allison_0
498,0,1,female,25.00,1,2,151.5500,S,Allison,Mrs,Hudson J C (Bessie Waldo Daniels),4,False,Allison_0
306,0,1,male,30.00,1,2,151.5500,S,Allison,Mr,Hudson Joshua Creighton,4,True,Allison_0
192,1,3,female,19.00,1,0,7.8542,S,Andersen-Jensen,Miss,Carla Christine Nielsine,2,False,Andersen-Jensen_0
13,0,3,male,39.00,1,5,31.2750,S,Andersson,Mr,Anders Johan,7,False,Andersson_0
610,0,3,female,39.00,1,5,31.2750,S,Andersson,Mrs,Anders Johan (Alfrida Konstantia Brogren),7,False,Andersson_0
541,0,3,female,9.00,4,2,31.2750,S,Andersson,Miss,Ingeborg Constanzia,7,False,Andersson_0
813,0,3,female,6.00,4,2,31.2750,S,Andersson,Miss,Ebba Iris Alfrida,7,False,Andersson_0
850,0,3,male,4.00,4,2,31.2750,S,Andersson,Master,Sigvard Harald Elias,7,False,Andersson_0
542,0,3,female,11.00,4,2,31.2750,S,Andersson,Miss,Sigrid Elisabeth,7,False,Andersson_0
119,0,3,female,2.00,4,2,31.2750,S,Andersson,Miss,Ellis Anna Maria,7,False,Andersson_0
68,1,3,female,17.00,4,2,7.9250,S,Andersson,Miss,Erna Alexandra,7,False,Andersson_1
214,0,3,female,38.00,4,2,7.7750,S,Andersson,Miss,Ida Augusta Margareta,7,True,Andersson_3
275,1,1,female,63.00,1,0,77.9583,S,Andrews,Miss,Kornelia Theodosia,2,False,Andrews_0
518,1,2,female,36.00,1,0,26.0000,S,Angle,Mrs,"William A (Florence ""Mary"" Agnes Hughes)",2,False,Angle_0
190,0,2,male,34.00,1,0,26.0000,S,Angle,Mr,William A,2,True,Angle_0
571,1,1,female,53.00,2,0,51.4792,S,Appleton,Mrs,Edward Dale (Charlotte Lamson),3,False,Appleton_0
49,0,3,female,18.00,1,0,17.8000,S,Arnold-Franchi,Mrs,Josef (Josefine Franchi),2,False,Arnold-Franchi_0
353,0,3,male,25.00,1,0,17.8000,S,Arnold-Franchi,Mr,Josef,2,False,Arnold-Franchi_0
174,0,3,male,40.00,1,5,31.3875,S,Asplund,Mr,Carl Oscar Vilhelm Gustafsson,7,True,Asplund_0
233,1,3,female,5.00,4,2,31.3875,S,Asplund,Miss,Lillian Gertrud,7,False,Asplund_0
379,0,3,male,5.00,4,2,31.3875,S,Asplund,Master,Carl Edgar,7,True,Asplund_0
261,1,3,male,3.00,4,2,31.3875,S,Asplund,Master,Edvin Rojj Felix,7,False,Asplund_0
182,0,3,male,9.00,4,2,31.3875,S,Asplund,Master,Clarence Gustaf Hugo,7,False,Asplund_0
25,1,3,female,38.00,1,5,31.3875,S,Asplund,Mrs,Carl Oscar (Selma Augusta Emilia Johansson),7,False,Asplund_0
154,0,3,male,13.00,4,2,31.3875,S,Asplund,Master,Filip Oscar,7,True,Asplund_0
202,0,1,male,47.00,1,0,227.5250,C,Astor,Col,John Jacob,2,True,Astor_0
700,1,1,female,18.00,1,0,227.5250,C,Astor,Mrs,John Jacob (Madeleine Talmadge Force),2,False,Astor_0
206,0,3,male,32.00,1,0,15.8500,S,Backstrom,Mr,Karl Alfred,2,False,Backstrom_0
85,1,3,female,33.00,3,0,15.8500,S,Backstrom,Mrs,Karl Alfred (Maria Mathilda Gustafsson),4,False,Backstrom_0
469,1,3,female,0.75,2,1,19.2583,C,Baclini,Miss,Helene Barbara,4,False,Baclini_0
448,1,3,female,5.00,2,1,19.2583,C,Baclini,Miss,Marie Catherine,4,False,Baclini_0
644,1,3,female,0.75,2,1,19.2583,C,Baclini,Miss,Eugenie,4,False,Baclini_0
858,1,3,female,24.00,0,3,19.2583,C,Baclini,Mrs,Solomon (Latifa Qurban),4,False,Baclini_0
702,0,3,female,18.00,0,1,14.4542,C,Barbara,Miss,Saiide,2,False,Barbara_0
362,0,3,female,45.00,0,1,14.4542,C,Barbara,Mrs,(Catherine David),2,False,Barbara_0
118,0,1,male,24.00,0,1,247.5208,C,Baxter,Mr,Quigg Edmond,2,False,Baxter_0
299,1,1,female,50.00,0,1,247.5208,C,Baxter,Mrs,James (Helene DeLaudeniere Chaput),2,False,Baxter_0
546,1,2,female,19.00,1,0,26.0000,S,Beane,Mrs,Edward (Ethel Clarke),2,False,Beane_0
543,1,2,male,32.00,1,0,26.0000,S,Beane,Mr,Edward,2,False,Beane_0
618,1,2,female,4.00,2,1,39.0000,S,Becker,Miss,Marion Louise,4,False,Becker_0
183,1,2,male,1.00,2,1,39.0000,S,Becker,Master,Richard F,4,False,Becker_0
178,0,2,female,36.00,0,3,39.0000,S,Becker,Mrs,Allen Oliver (Nellie E Baumgardner),4,True,Becker_0
326,0,2,female,12.00,2,1,39.0000,S,Becker,Miss,Ruth Elizabeth,4,True,Becker_0
871,1,1,female,47.00,1,1,52.5542,S,Beckwith,Mrs,Richard Leonard (Sallie Monypeny),3,False,Beckwith_0
248,1,1,male,37.00,1,1,52.5542,S,Beckwith,Mr,Richard Leonard,3,False,Beckwith_0
291,1,1,female,19.00,1,0,91.0792,C,Bishop,Mrs,Dickinson H (Helen Walton),2,False,Bishop_0
484,1,1,male,25.00,1,0,91.0792,C,Bishop,Mr,Dickinson H,2,False,Bishop_0
852,0,3,female,9.00,1,1,15.2458,C,Boulos,Miss,Nourelain,3,False,Boulos_0
140,0,3,female,NaN,0,2,15.2458,C,Boulos,Mrs,Joseph (Sultana),3,False,Boulos_0
80,0,3,male,6.00,1,1,15.2458,C,Boulos,Master,Akar,3,True,Boulos_0
188,0,3,male,40.00,1,1,15.5000,Q,Bourke,Mr,John,3,False,Bourke_0
657,0,3,female,32.00,1,1,15.5000,Q,Bourke,Mrs,John (Catherine),3,False,Bourke_0
593,0,3,female,NaN,0,2,7.7500,Q,Bourke,Miss,Mary,3,False,Bourke_1
356,1,1,female,22.00,0,1,55.0000,S,Bowerman,Miss,Elsie Edith,2,False,Bowerman_0
0,0,3,male,22.00,1,0,7.2500,S,Braund,Mr,Owen Harris,2,False,Braund_0
477,0,3,male,29.00,1,0,7.0458,S,Braund,Mr,Lewis Richard,2,False,Braund_1
684,0,2,male,60.00,1,1,39.0000,S,Brown,Mr,Thomas William Solomon,3,False,Brown_2
175,0,2,female,15.00,0,2,39.0000,S,Brown,Miss,Edith Eileen,3,True,Brown_2
670,1,2,female,40.00,1,1,39.0000,S,Brown,Mrs,Thomas William Solomon (Elizabeth Catherine F...,3,False,Brown_2
356,0,1,female,59.00,2,0,51.4792,S,Brown,Mrs,John Murray (Caroline Lane Lamson),3,True,Brown_3
728,0,2,male,25.00,1,0,26.0000,S,Bryhl,Mr,Kurt Arnold Gottfrid,2,False,Bryhl_0
275,0,2,female,20.00,1,0,26.0000,S,Bryhl,Miss,Dagmar Jenny Ingeborg,2,True,Bryhl_0
78,1,2,male,0.83,0,2,29.0000,S,Caldwell,Master,Alden Gates,3,False,Caldwell_0
323,1,2,female,22.00,1,1,29.0000,S,Caldwell,Mrs,Albert Francis (Sylvia Mae Harbaugh),3,False,Caldwell_0
7,0,2,male,26.00,1,1,29.0000,S,Caldwell,Mr,Albert Francis,3,True,Caldwell_0
366,0,3,male,NaN,1,0,14.4583,C,Caram,Mr,Joseph,2,True,Caram_0
578,0,3,female,NaN,1,0,14.4583,C,Caram,Mrs,Joseph (Maria Elias),2,False,Caram_0
343,0,1,female,58.00,0,1,512.3292,C,Cardeza,Mrs,James Warburton Martinez (Charlotte Wardle Dr...,2,True,Cardeza_0
679,1,1,male,36.00,0,1,512.3292,C,Cardeza,Mr,Thomas Drake Martinez,2,False,Cardeza_0
249,0,2,male,54.00,1,0,26.0000,S,Carter,Rev,Ernest Courtenay,2,False,Carter_0
854,0,2,female,44.00,1,0,26.0000,S,Carter,Mrs,Ernest Courtenay (Lilian Hughes),2,False,Carter_0
435,1,1,female,14.00,1,2,120.0000,S,Carter,Miss,Lucile Polk,4,False,Carter_1
763,1,1,female,36.00,1,2,120.0000,S,Carter,Mrs,William Ernest (Lucile Polk),4,False,Carter_1
802,1,1,male,11.00,1,2,120.0000,S,Carter,Master,William Thornton II,4,False,Carter_1
390,1,1,male,36.00,1,2,120.0000,S,Carter,Mr,William Ernest,4,False,Carter_1
741,0,1,male,36.00,1,0,78.8500,S,Cavendish,Mr,Tyrell William,2,False,Cavendish_0
96,0,1,female,76.00,1,0,78.8500,S,Cavendish,Mrs,Tyrell William (Julia Florence Siegel),2,True,Cavendish_0
14,0,1,female,47.00,1,0,61.1750,S,Chaffee,Mrs,Herbert Fuller (Carrie Constance Toogood),2,True,Chaffee_0
92,0,1,male,46.00,1,0,61.1750,S,Chaffee,Mr,Herbert Fuller,2,False,Chaffee_0
809,1,1,female,33.00,1,0,53.1000,S,Chambers,Mrs,Norman Campbell (Bertha Griggs),2,False,Chambers_0
724,1,1,male,27.00,1,0,53.1000,S,Chambers,Mr,Norman Campbell,2,False,Chambers_0
594,0,2,male,37.00,1,0,26.0000,S,Chapman,Mr,John Henry,2,False,Chapman_0
119,0,2,female,29.00,1,0,26.0000,S,Chapman,Mrs,John Henry (Sara Elizabeth Lawry),2,True,Chapman_0
166,1,1,female,NaN,0,1,55.0000,S,Chibnall,Mrs,(Edith Martha Bowerman),2,False,Chibnall_0
580,1,2,female,25.00,1,1,30.0000,S,Christy,Miss,Julie Rachel,3,False,Christy_0
241,0,2,female,45.00,0,2,30.0000,S,Christy,Mrs,(Alice Frances),3,True,Christy_0
115,0,3,male,18.00,1,0,14.4542,C,Chronopoulos,Mr,Demetrios,2,True,Chronopoulos_0
73,0,3,male,26.00,1,0,14.4542,C,Chronopoulos,Mr,Apostolos,2,False,Chronopoulos_0
272,0,1,female,26.00,1,0,136.7792,C,Clark,Mrs,Walter Miller (Virginia McDowell),2,True,Clark_0
252,0,1,male,27.00,1,0,136.7792,C,Clark,Mr,Walter Miller,2,True,Clark_0
426,1,2,female,28.00,1,0,26.0000,S,Clarke,Mrs,Charles V (Ada Maria Winfield),2,False,Clarke_0
328,0,2,male,29.00,1,0,26.0000,S,Clarke,Mr,Charles Valentine,2,True,Clarke_0
237,1,2,female,8.00,0,2,26.2500,S,Collyer,Miss,"Marjorie ""Lottie""",3,False,Collyer_0
637,0,2,male,31.00,1,1,26.2500,S,Collyer,Mr,Harvey,3,False,Collyer_0
801,1,2,female,31.00,1,1,26.2500,S,Collyer,Mrs,Harvey (Charlotte Annie Tate),3,False,Collyer_0
835,1,1,female,39.00,1,1,83.1583,C,Compton,Miss,Sara Rebecca,3,False,Compton_0
179,0,1,female,64.00,0,2,83.1583,C,Compton,Mrs,Alexander Taylor (Mary Eliza Ingersoll),3,True,Compton_0
181,0,1,male,37.00,1,1,83.1583,C,Compton,Mr,Alexander Taylor Jr,3,True,Compton_0
77,0,1,female,55.00,2,0,25.7000,S,Cornell,Mrs,Robert Clifford (Malvina Helen Lamson),3,True,Cornell_0
489,1,3,male,9.00,1,1,15.9000,S,Coutts,Master,"Eden Leslie ""Neville""",3,False,Coutts_0
348,1,3,male,3.00,1,1,15.9000,S,Coutts,Master,"William Loch ""William""",3,False,Coutts_0
49,0,3,female,36.00,0,2,15.9000,S,Coutts,Mrs,"William (Winnie Minnie"" Treanor)""",3,True,Coutts_0
125,0,3,female,17.00,0,1,16.1000,S,Cribb,Miss,Laura Alice,2,True,Cribb_0
160,0,3,male,44.00,0,1,16.1000,S,Cribb,Mr,John Hatfield,2,False,Cribb_0
745,0,1,male,70.00,1,1,71.0000,S,Crosby,Capt,Edward Gifford,3,False,Crosby_0
540,1,1,female,36.00,0,2,71.0000,S,Crosby,Miss,Harriet R,3,False,Crosby_0
305,0,1,female,64.00,1,1,26.5500,S,Crosby,Mrs,Edward Gifford (Catherine Elizabeth Halstead),3,True,Crosby_1
1,1,1,female,38.00,1,0,71.2833,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),2,False,Cumings_0
234,0,1,male,39.00,1,0,71.2833,C,Cumings,Mr,John Bradley,2,True,Cumings_0
616,0,3,male,34.00,1,1,14.4000,S,Danbom,Mr,Ernst Gilbert,3,False,Danbom_0
201,0,3,male,0.33,0,2,14.4000,S,Danbom,Master,Gilbert Sigvard Emanuel,3,True,Danbom_0
423,0,3,female,28.00,1,1,14.4000,S,Danbom,Mrs,Ernst Gilbert (Anna Sigrid Maria Brogren),3,False,Danbom_0
671,0,1,male,31.00,1,0,52.0000,S,Davidson,Mr,Thornton,2,False,Davidson_0
92,0,1,female,27.00,1,2,52.0000,S,Davidson,Mrs,Thornton (Orian Hays),4,True,Davidson_0
330,0,2,female,48.00,0,2,36.7500,S,Davies,Mrs,John Morgan (Elizabeth Agnes Mary White),3,True,Davies_1
549,1,2,male,8.00,1,1,36.7500,S,Davies,Master,John Morgan Jr,3,False,Davies_1
9,0,3,male,21.00,2,0,24.1500,S,Davies,Mr,John Samuel,3,True,Davies_2
565,0,3,male,24.00,2,0,24.1500,S,Davies,Mr,Alfred J,3,False,Davies_2
187,0,3,male,17.00,2,0,8.0500,S,Davies,Mr,Joseph,3,True,Davies_3
58,0,3,male,NaN,1,0,16.1000,S,Davison,Mr,Thomas Henry,2,True,Davison_0
347,1,3,female,NaN,1,0,16.1000,S,Davison,Mrs,Thomas Henry (Mary E Finck),2,False,Davison_0
788,1,3,male,1.00,1,2,20.5750,S,Dean,Master,Bertram Vere,4,False,Dean_0
354,0,3,female,0.17,1,2,20.5750,S,Dean,Miss,"Elizabeth Gladys Millvina""""",4,True,Dean_0
93,0,3,male,26.00,1,2,20.5750,S,Dean,Mr,Bertram Frank,4,False,Dean_0
32,0,3,female,33.00,1,2,20.5750,S,Dean,Mrs,Bertram (Eva Georgetta Light),4,True,Dean_0
690,1,1,male,31.00,1,0,57.0000,S,Dick,Mr,Albert Adrian,2,False,Dick_0
781,1,1,female,17.00,1,0,57.0000,S,Dick,Mrs,Albert Adrian (Vera Gillespie),2,False,Dick_0
293,0,1,male,53.00,1,1,81.8583,S,Dodge,Dr,Washington,3,True,Dodge_0
445,1,1,male,4.00,0,2,81.8583,S,Dodge,Master,Washington,3,False,Dodge_0
374,0,1,female,54.00,1,1,81.8583,S,Dodge,Mrs,Washington (Ruth Vidaver),3,True,Dodge_0
98,1,2,female,34.00,0,1,23.0000,S,Doling,Mrs,John T (Ada Julia Bone),2,False,Doling_0
651,1,2,female,18.00,0,1,23.0000,S,Doling,Miss,Elsie,2,False,Doling_0
239,0,1,female,48.00,1,0,106.4250,C,Douglas,Mrs,Walter Donald (Mahala Dutton),2,True,Douglas_0
544,0,1,male,50.00,1,0,106.4250,C,Douglas,Mr,Walter Donald,2,False,Douglas_0
184,0,1,female,27.00,1,1,247.5208,C,Douglas,Mrs,Frederick Charles (Mary Helene Baxter),3,True,Douglas_1
416,1,2,female,34.00,1,1,32.5000,S,Drew,Mrs,James Vivian (Lulu Thorne Christian),3,False,Drew_0
247,0,2,male,42.00,1,1,32.5000,S,Drew,Mr,James Vivian,3,True,Drew_0
194,0,2,male,8.00,0,2,32.5000,S,Drew,Master,Marshall Brines,3,True,Drew_0
556,1,1,female,48.00,1,0,39.6000,C,Duff Gordon,Lady,"(Lucille Christiana Sutherland) (""Mrs Morgan"")",2,False,Duff Gordon_0
599,1,1,male,49.00,1,0,56.9292,C,Duff Gordon,Sir,"Cosmo Edmund (""Mr Morgan"")",2,False,Duff Gordon_1
220,0,2,female,30.00,1,0,13.8583,C,Duran y More,Miss,Florentina,2,True,Duran y More_0
866,1,2,female,27.00,1,0,13.8583,C,Duran y More,Miss,Asuncion,2,False,Duran y More_0
90,0,3,female,22.00,1,0,13.9000,S,Dyker,Mrs,Adolf Fredrik (Anna Elisabeth Judith Andersson),2,True,Dyker_0
172,0,3,male,23.00,1,0,13.9000,S,Dyker,Mr,Adolf Fredrik,2,True,Dyker_0
150,0,1,female,23.00,0,1,83.1583,C,Earnshaw,Mrs,Boulton (Olive Potter),2,True,Earnshaw_0
352,0,3,male,15.00,1,1,7.2292,C,Elias,Mr,Tannous,3,False,Elias_0
337,0,3,male,39.00,0,2,7.2292,C,Elias,Mr,Joseph,3,True,Elias_0
532,0,3,male,17.00,1,1,7.2292,C,Elias,Mr,Joseph Jr,3,False,Elias_0
496,1,1,female,54.00,1,0,78.2667,C,Eustis,Miss,Elizabeth Mussey,2,False,Eustis_0
53,1,2,female,29.00,1,0,26.0000,S,Faunthorpe,Mrs,Lizzie (Elizabeth Anne Wilkinson),2,False,Faunthorpe_0
277,0,2,male,40.00,1,0,26.0000,S,Faunthorpe,Mr,Harry,2,True,Faunthorpe_0
147,0,3,female,9.00,2,2,34.3750,S,Ford,Miss,"Robina Maggie ""Ruby""",5,False,Ford_0
436,0,3,female,21.00,2,2,34.3750,S,Ford,Miss,"Doolina Margaret ""Daisy""",5,False,Ford_0
736,0,3,female,48.00,1,3,34.3750,S,Ford,Mrs,Edward (Margaret Ann Watson),5,False,Ford_0
167,0,3,male,18.00,2,2,34.3750,S,Ford,Mr,Edward Watson,5,True,Ford_0
86,0,3,male,16.00,1,3,34.3750,S,Ford,Mr,William Neal,5,False,Ford_0
88,1,1,female,23.00,3,2,263.0000,S,Fortune,Miss,Mabel Helen,6,False,Fortune_0
53,0,1,female,28.00,3,2,263.0000,S,Fortune,Miss,Ethel Flora,6,True,Fortune_0
341,1,1,female,24.00,3,2,263.0000,S,Fortune,Miss,Alice Elizabeth,6,False,Fortune_0
27,0,1,male,19.00,3,2,263.0000,S,Fortune,Mr,Charles Alexander,6,False,Fortune_0
69,0,1,female,60.00,1,4,263.0000,S,Fortune,Mrs,Mark (Mary McDougald),6,True,Fortune_0
438,0,1,male,64.00,1,4,263.0000,S,Fortune,Mr,Mark,6,False,Fortune_0
334,1,1,female,NaN,1,0,133.6500,S,Frauenthal,Mrs,Henry William (Clara Heinsheimer),2,False,Frauenthal_0
660,1,1,male,50.00,2,0,133.6500,S,Frauenthal,Dr,Henry William,3,False,Frauenthal_0
404,0,1,male,43.00,1,0,27.7208,C,Frauenthal,Mr,Isaac Gerald,2,True,Frauenthal_1
397,0,1,female,48.00,1,1,79.2000,C,Frolicher-Stehli,Mrs,Maxmillian (Margaretha Emerentia Stehli),3,True,Frolicher-Stehli_0
587,1,1,male,60.00,1,1,79.2000,C,Frolicher-Stehli,Mr,Maxmillian,3,False,Frolicher-Stehli_0
539,1,1,female,22.00,0,2,49.5000,C,Frolicher,Miss,Hedwig Margaritha,3,False,Frolicher_0
137,0,1,male,37.00,1,0,53.1000,S,Futrelle,Mr,Jacques Heath,2,False,Futrelle_0
3,1,1,female,35.00,1,0,53.1000,S,Futrelle,Mrs,Jacques Heath (Lily May Peel),2,False,Futrelle_0
401,0,2,male,38.00,1,0,21.0000,S,Gale,Mr,Harry,2,True,Gale_0
405,0,2,male,34.00,1,0,21.0000,S,Gale,Mr,Shadrach,2,False,Gale_0
402,0,1,female,22.00,0,1,59.4000,C,Gibson,Miss,Dorothy Winifred,2,True,Gibson_0
368,0,1,female,45.00,0,1,59.4000,C,Gibson,Mrs,Leonard (Pauline C Boeson),2,True,Gibson_0
861,0,2,male,21.00,1,0,11.5000,S,Giles,Mr,Frederick Edward,2,False,Giles_0
370,0,2,male,21.00,1,0,11.5000,S,Giles,Mr,Edgar,2,True,Giles_0
453,1,1,male,49.00,1,0,89.1042,C,Goldenberg,Mr,Samuel L,2,False,Goldenberg_0
849,1,1,female,NaN,1,0,89.1042,C,Goldenberg,Mrs,Samuel L (Edwiga Grabowska),2,False,Goldenberg_0
328,1,3,female,31.00,1,1,20.5250,S,Goldsmith,Mrs,Frank John (Emily Alice Brown),3,False,Goldsmith_0
165,1,3,male,9.00,0,2,20.5250,S,Goldsmith,Master,"Frank John William ""Frankie""",3,False,Goldsmith_0
548,0,3,male,33.00,1,1,20.5250,S,Goldsmith,Mr,Frank John,3,False,Goldsmith_0
386,0,3,male,1.00,5,2,46.9000,S,Goodwin,Master,Sidney Leonard,8,False,Goodwin_0
678,0,3,female,43.00,1,6,46.9000,S,Goodwin,Mrs,Frederick (Augusta Tyler),8,False,Goodwin_0
139,0,3,male,40.00,1,6,46.9000,S,Goodwin,Mr,Charles Frederick,8,True,Goodwin_0
59,0,3,male,11.00,5,2,46.9000,S,Goodwin,Master,William Frederick,8,False,Goodwin_0
140,0,3,female,10.00,5,2,46.9000,S,Goodwin,Miss,Jessie Allis,8,True,Goodwin_0
71,0,3,female,16.00,5,2,46.9000,S,Goodwin,Miss,Lillian Amy,8,False,Goodwin_0
480,0,3,male,9.00,5,2,46.9000,S,Goodwin,Master,Harold Victor,8,False,Goodwin_0
683,0,3,male,14.00,5,2,46.9000,S,Goodwin,Mr,Charles Edward,8,False,Goodwin_0
332,0,1,male,38.00,0,1,153.4625,S,Graham,Mr,George Edward,2,False,Graham_0
268,1,1,female,58.00,0,1,153.4625,S,Graham,Mrs,William Thompson (Edith Junkins),2,False,Graham_0
350,0,1,female,45.00,0,1,63.3583,C,Greenfield,Mrs,Leo David (Blanche Strouse),2,True,Greenfield_0
97,1,1,male,23.00,0,1,63.3583,C,Greenfield,Mr,William Bertram,2,False,Greenfield_0
104,0,3,male,37.00,2,0,7.9250,S,Gustafsson,Mr,Anders Vilhelm,3,False,Gustafsson_0
392,0,3,male,28.00,2,0,7.9250,S,Gustafsson,Mr,Johan Birger,3,False,Gustafsson_0
490,0,3,male,NaN,1,0,19.9667,S,Hagland,Mr,Konrad Mathias Reiersen,2,False,Hagland_0
451,0,3,male,NaN,1,0,19.9667,S,Hagland,Mr,Ingvald Olai Olsen,2,False,Hagland_0
142,1,3,female,24.00,1,0,15.8500,S,Hakkarainen,Mrs,Pekka Pietari (Elin Matilda Dolck),2,False,Hakkarainen_0
403,0,3,male,28.00,1,0,15.8500,S,Hakkarainen,Mr,Pekka Pietari,2,False,Hakkarainen_0
755,1,2,male,0.67,1,1,14.5000,S,Hamalainen,Master,Viljo,3,False,Hamalainen_0
247,1,2,female,24.00,0,2,14.5000,S,Hamalainen,Mrs,William (Anna),3,False,Hamalainen_0
704,0,3,male,26.00,1,0,7.8542,S,Hansen,Mr,Henrik Juul,2,False,Hansen_0
860,0,3,male,41.00,2,0,14.1083,S,Hansen,Mr,Claus Peter,3,False,Hansen_1
309,0,3,female,45.00,1,0,14.1083,S,Hansen,Mrs,Claus Peter (Jennie L Howard),2,True,Hansen_1
370,1,1,male,25.00,1,0,55.4417,C,Harder,Mr,George Achilles,2,False,Harder_0
364,0,1,female,25.00,1,0,55.4417,C,Harder,Mrs,George Achilles (Dorothy Annan),2,True,Harder_0
52,1,1,female,49.00,1,0,76.7292,C,Harper,Mrs,Henry Sleeper (Myna Haxtun),2,False,Harper_0
645,1,1,male,48.00,1,0,76.7292,C,Harper,Mr,Henry Sleeper,2,False,Harper_0
720,1,2,female,6.00,0,1,33.0000,S,Harper,Miss,"Annie Jessie ""Nina""",2,False,Harper_1
848,0,2,male,28.00,0,1,33.0000,S,Harper,Rev,John,2,False,Harper_1
62,0,1,male,45.00,1,0,83.4750,S,Harris,Mr,Henry Birkhardt,2,False,Harris_0
230,1,1,female,35.00,1,0,83.4750,S,Harris,Mrs,Henry Birkhardt (Irene Wallach),2,False,Harris_0
314,0,2,male,43.00,1,1,26.2500,S,Hart,Mr,Benjamin,3,False,Hart_0
440,1,2,female,45.00,1,1,26.2500,S,Hart,Mrs,Benjamin (Esther Ada Bloomfield),3,False,Hart_0
535,1,2,female,7.00,0,2,26.2500,S,Hart,Miss,Eva Miriam,3,False,Hart_0
308,0,1,male,55.00,1,1,93.5000,S,Hays,Mr,Charles Melville,3,True,Hays_1
820,1,1,female,52.00,1,1,93.5000,S,Hays,Mrs,Charles Melville (Clara Jennings Gregg),3,False,Hays_1
615,1,2,female,24.00,1,2,65.0000,S,Herman,Miss,Alice,4,False,Herman_0
385,0,2,female,24.00,1,2,65.0000,S,Herman,Miss,Kate,4,True,Herman_0
754,1,2,female,48.00,1,2,65.0000,S,Herman,Mrs,Samuel (Jane Laver),4,False,Herman_0
353,0,2,male,49.00,1,2,65.0000,S,Herman,Mr,Samuel,4,True,Herman_0
655,0,2,male,24.00,2,0,73.5000,S,Hickman,Mr,Leonard Mark,3,False,Hickman_0
665,0,2,male,32.00,2,0,73.5000,S,Hickman,Mr,Lewis,3,False,Hickman_0
120,0,2,male,21.00,2,0,73.5000,S,Hickman,Mr,Stanley George,3,False,Hickman_0
238,0,2,female,18.00,1,1,13.0000,S,Hiltunen,Miss,Marta,3,True,Hiltunen_0
523,1,1,female,44.00,0,1,57.9792,C,Hippach,Mrs,Louis Albert (Ida Sophia Fischer),2,False,Hippach_0
329,1,1,female,16.00,0,1,57.9792,C,Hippach,Miss,Jean Gertrude,2,False,Hippach_0
4,0,3,female,22.00,1,1,12.2875,S,Hirvonen,Mrs,Alexander (Helga E Lindqvist),3,True,Hirvonen_0

In [103]:
fams["Family"].value_counts()

Sage_0                    11
Andersson_0                9
Goodwin_0                  8
Asplund_0                  7
Skoog_0                    6
Panula_0                   6
Rice_0                     6
Fortune_0                  6
Ryerson_0                  5
Lefebre_0                  5
Ford_0                     5
Palsson_0                  5
Davies_1                   5
Laroche_0                  4
West_0                     4
Baclini_0                  4
Herman_0                   4
Dean_0                     4
Harper_0                   4
Allison_0                  4
Johnston_0                 4
Brown_1                    4
Carter_1                   4
Becker_0                   4
Bourke_0                   3
Crosby_0                   3
Klasen_0                   3
Goldsmith_0                3
Thayer_0                   3
Collyer_0                  3
Widener_0                  3
van Billiard_0             3
Rosblom_0                  3
Wick_0                     3
Elias_0                    3
Coutts_0                   3
Drew_0                     3
Van Impe_0                 3
Danbom_0                   3
Spedden_0                  3
Hart_0                     3
Touma_0                    3
McCoy_0                    3
Abbott_0                   3
Dodge_0                    3
Boulos_0                   3
Taussig_0                  3
Quick_0                    3
Navratil_0                 3
Nakid_0                    3
Caldwell_0                 3
Wells_0                    3
Peter_0                    3
Mallet_0                   3
Moubarek_0                 3
Hickman_0                  3
Johnson_0                  3
Samaan_0                   3
Sandstrom_0                3
Compton_0                  3
Peacock_0                  3
Silvey_0                   2
Jefferys_0                 2
Howard_0                   2
Bryhl_0                    2
Straus_0                   2
Hagland_0                  2
Goldenberg_0               2
Kenyon_0                   2
Snyder_0                   2
Duran y More_0             2
Smith_1                    2
Khalil_0                   2
Louch_0                    2
Thorneycroft_0             2
Clarke_0                   2
Dyker_0                    2
Stengel_0                  2
Phillips_1                 2
Clark_0                    2
Ware_0                     2
Minahan_1                  2
Richards_0                 2
Gale_0                     2
Gibson_0                   2
Giles_0                    2
Aks_0                      2
Rothschild_0               2
Angle_0                    2
Hansen_1                   2
Astor_0                    2
Karun_0                    2
Dick_0                     2
Ilmakangas_0               2
Cardeza_0                  2
Cavendish_0                2
McNamee_0                  2
Marvin_0                   2
Taylor_0                   2
Moor_0                     2
Thomas_0                   2
Kimball_0                  2
Yasbeck_0                  2
Hays_1                     2
Lindell_0                  2
Chapman_0                  2
Frolicher-Stehli_0         2
Christy_0                  2
Caram_0                    2
de Messemaeker_0           2
Duff Gordon_0              2
Lines_0                    2
Douglas_0                  2
Beane_0                    2
Chambers_0                 2
Hocking_0                  2
Braund_0                   2
del Carlo_0                2
Wiklund_0                  2
Hold_0                     2
Nicola-Yarred_0            2
Greenfield_0               2
Kiernan_0                  2
Turpin_0                   2
Lennon_0                   2
Olsen_1                    2
Arnold-Franchi_0           2
O'Brien_0                  2
Kink-Heilmann_0            2
Faunthorpe_0               2
Cribb_0                    2
Williams_1                 2
Harder_0                   2
Pears_0                    2
Ostby_0                    2
Hakkarainen_0              2
Harris_0                   2
Weisz_0                    2
Kink_0                     2
Robins_0                   2
Baxter_0                   2
Jussila_0                  2
Zabour_0                   2
Moran_1                    2
Gustafsson_0               2
White_0                    2
Chronopoulos_0             2
Chaffee_0                  2
Kantor_0                   2
Hoyt_0                     2
Newell_0                   2
Murphy_0                   2
Hippach_0                  2
Mellinger_0                2
Spencer_0                  2
Bishop_0                   2
Penasco y Castellana_0     2
Abelson_0                  2
Lahtinen_0                 2
Frauenthal_0               2
Meyer_0                    2
Nasser_0                   2
Davison_0                  2
Futrelle_0                 2
Cumings_0                  2
Barbara_0                  2
Warren_0                   2
Vander Planke_1            2
Graham_0                   2
Doling_0                   2
Lobb_0                     2
Hamalainen_0               2
Beckwith_0                 2
Carter_0                   2
Holverson_0                2
Ahlin_0                    1
Backstrom_0                1
Davidson_1                 1
Cornell_0                  1
Mock_0                     1
Shelley_0                  1
Potter_0                   1
Schabert_0                 1
Vander Planke_2            1
Hansen_2                   1
Vander Planke_0            1
Hiltunen_0                 1
Earnshaw_0                 1
Douglas_1                  1
Hirvonen_1                 1
Wilkes_0                   1
Thomas_1                   1
Madill_0                   1
Robert_0                   1
Renouf_0                   1
Minahan_0                  1
Frolicher_0                1
Strom_1                    1
Parrish_0                  1
Eustis_0                   1
Hirvonen_0                 1
Persson_0                  1
Hocking_1                  1
Natsch_0                   1
Andrews_0                  1
Petterson_0                1
Richards_1                 1
Silven_0                   1
Bowerman_0                 1
Jacobsohn_0                1
Appleton_0                 1
Backstrom_1                1
Stephenson_0               1
Strom_0                    1
Jacobsohn_1                1
Andersen-Jensen_0          1
Newell_1                   1
Frauenthal_1               1
Lindqvist_0                1
Chibnall_0                 1
Davidson_0                 1
Nicholls_0                 1
Newsom_0                   1
Jensen_1                   1
Renouf_1                   1
Hogeboom_0                 1
Kink-Heilmann_1            1
Name: Family, dtype: int64

# Evtl. besser Familien anhand der Fare und des Nachnamens zu bilden? (selber Fare und selber Nachname => eine Familie)